mysite/myapp/urls.py
from django.urls import path
from .views import indexItem
from .views import index
from .views import add_item
app_name = 'myapp'

urlpatterns = [
    path('', index),
    path('<int:my_id>/', indexItem, name='detail'),
    path('additem/', add_item, name='add_item'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls', namespace='myapp')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/myapp/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=20)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    description = models.TextField()
    image = models.ImageField(blank=True, null=True, upload_to='images')

    def __str__(self):
        return self.name

mysite/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product


# Create your views here.
def index(request):
    items = Product.objects.all()
    context = {
        'items': items
    }
    return render(request, 'index.html', context)


def indexItem(request, my_id):
    item = Product.objects.get(id=my_id)
    context = {
        'item': item
    }
    return render(request, 'detail.html', context=context)

def add_item(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        image = request.FILES['upload']
        item = Product(name=name, price=price, description=description, image=image)
        item.save()
    return render(request, 'additem.html')

mysite/myapp/templates/additem.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" placeholder="Name..." name="name" id="name">
    <input type="number" placeholder="Price..." name="price" id="price">
    <input type="text" placeholder="Description..." name="description" id="description">
    <input type="file" accept="image/*" name="upload" id="upload">
    <button type="submit" name="Add Item" value="Add Item">Add Item</button>
</form>

mysite/myapp/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
    <title>7Store</title>
</head>
<body>

    {% include "navbar.html" %}

    {% block content %}

    {% endblock content %}
</body>
</html>

mysite/myapp/templates/detail.html
{% extends "base.html" %}
{% load humanize %}
{% load static %}
<html lang="en">
    {% block content %}
        <div class="flex p-10 w-full h-300">
            <img class="w-1/3" src="{{ item.image.url }}" alt="">
            <div class="w-2/3 text-xl ml-10 mt-5">
                <p class="mt-5">{{ item.name }}</p>
                <p class="mt-5 text-green-500">{{ item.price | intcomma }}</p>
                <p class="mt-5 text-gray-500">{{ item.description }}</p>
            </div>
        </div>
    {% endblock content %}
</html>

mysite/myapp/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <main class="mt-10 mx-auto max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
        <div class="sm:text-center lg:text-left">
            <h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
                <span class="block xl:inline">ექსკლუზიური საქონელი</span>
                <span class="block xl:inline text-green-500">სუპერ ფასად</span>
            </h1>
            <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">საქონლის შეკვეთა შეგიძლიათ დედამიწის ნებისმიერი წერტილიდან. მიტანა უფასოა</p>
        </div>
        <div class="p-10 grid grid-cols-1 sm:gid-cols-1 md:grid-cols-3 xl:grid-cols-3 lg:grid-cols-3 gap-3">
        {% for item in items %}
        <a href="{% url 'myapp:detail' item.id %}">
            <div class="rounded overflow-hidden shadow-lg">
                <img class="w-full h-[400px]" src="{{item.image.url}}" alt="">
                <div class="px-6 py-4">
                    <p class="font-bold text-xl mb-2">{{item.name}}</p>
                    <p class="font-bold text-xl text-green-500 mb-2">$ {{item.price}}</p>
                    <p class="text-gray-700 text-base">{{item.description}}</p>
                </div>
            </div>
        </a>
    </main>
    {% endfor %}
    </div>
{% endblock content %}

mysite/myapp/templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<nav class="bg-white shadow-lg">
    <div class="max-w-6xl mx-auto px-4">
        <div class="flex justify-between">
            <div class="flex space-x-7">
                <div class="flex">
                    <a href="#" class="flex items-center px-2 py-4">
                        <img class="h-8 w-8" src="{% static 'myapp/images/shop.png' %}" alt="logo" />
                        <span class="text-gray-500 text-4xl">Pro Shop</span></a>
                </div>
                <div class="items-center flex space-x-1">
                    <a href="#" class="py-4 px-2 text-gray-500 font-semibold border-b-4 border-green-500">Home</a>
                    <a href="#" class="py-4 px-2 text-gray-500 font-semibold">About</a>
                    <a href="#" class="py-4 px-2 text-gray-500 font-semibold">Contacts</a>
                    <a href="#" class="py-4 px-2 text-gray-500 font-semibold">Place</a>
                </div>
            </div>
        </div>
    </div>
</nav>
</html>